# docker-compose.yml
version: "3.8"

services:
  openjdk:
    image: openjdk:11
    container_name: openjdk-container
    networks:
      - app-network

  gcc:
    image: gcc:latest
    container_name: gcc-container
    networks:
      - app-network
  compile:
    build:
      dockerfile: ./apps/compile/Dockerfile
      target: development
    # image: lochoang174/dev-arena-be-compile:latest
    container_name: compile-service
    command: npm run start:compile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
    privileged: true
  main:
    # image: lochoang174/dev-arena-be-main:latest
    build:
      dockerfile: ./apps/main/Dockerfile
      target: development
    container_name: main-service
    command: npm run start:dev
    ports:
      - "3001:3001"
    env_file:
      - ./apps/main/.env
    networks:
      - app-network
    depends_on:
      - compile

networks:
  app-network:
    driver: bridge
