// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.6.1
//   protoc               v3.20.3
// source: proto/compile.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "compile";

export interface CompileRequest {
  /** Mã nguồn để kiểm tra */
  code: string;
  /** Mã nguồn giải pháp */
  codeSolution: string;
  /** Danh sách các testcase */
  testcases: TestCase[];
}

export interface TestCase {
  /** Mảng các input của testcase */
  inputs: string[];
}

export interface CompileStatus {
  testCaseIndex: number;
  isCorrect: boolean;
  output: string;
  outputExpect: string;
}

export const COMPILE_PACKAGE_NAME = "compile";

export interface CompileServiceClient {
  /** Hàm xử lý compile code với danh sách testcase */

  runCompile(request: CompileRequest): Observable<CompileStatus>;
}

export interface CompileServiceController {
  /** Hàm xử lý compile code với danh sách testcase */

  runCompile(request: CompileRequest): Observable<CompileStatus>;
}

export function CompileServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["runCompile"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CompileService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CompileService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const COMPILE_SERVICE_NAME = "CompileService";
